name: Build, Publish and Deploy JIB Image

on:
  release:
    types: [created, edited]

jobs:
  build:
    environment: DEV
    permissions:
      contents: write
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-22.04
          - platform: linux/arm64
            runner: ubuntu-22.04-arm
    runs-on: ${{matrix.runner}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.0

      - name: Set up Build environment
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Docker Authenticate
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push JIB Image
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          "./gradlew jib"

  deploy-azure:
    environment: DEV
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/arm-deploy@v2
        with:
          deploymentName: ${{ github.run_number }}
          resourceGroupName: ${{ vars.AZURE_RESOURCEGROUP_NAME }}
          template: ./deploy/main.bicep
          parameters: environmentType=nonprod