name: Build and Publish JIB Image

on:
  release:
    types: [created, edited]

jobs:
  buildArm:
    environment: DEV
    runs-on: ubuntu-22.04-arm
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.0

      - name: Set up Build environment
        uses: actions/setup-java@v4.7.1
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5.0.0

      - name: Docker Authenticate
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push JIB Image
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          "./gradlew jib"

